name: Daily Profile GIF Updater

on:
  schedule:
    - cron: '0 0 * * *' # Запуск каждый день в полночь по UTC
  workflow_dispatch: # Позволит  запустить скрипт вручную кнопкой

jobs:
  update-gif:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pick random GIF and update README
        run: |
          # Выбираем случайное число от 1 до 58
          RANDOM_NUM=$((1 + RANDOM % 58))
          echo "Selected GIF number: $RANDOM_NUM"
          
          # Заменяем старую картинку между нашими тегами-маркерами
          sed -i '/<!-- START_GIF -->/,/<!-- END_GIF -->/{//!d;}' README.md
          sed -i '/<!-- START_GIF -->/a !\[Солнечная система\]\(gifs/'"$RANDOM_NUM"'.gif\)' README.md

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff-index --quiet HEAD || git commit -m "Автообновление: установлена гифка №$RANDOM_NUM"
          git push
