name: Daily Profile GIF Updater

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-gif:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pick random GIF and update README
        run: |
          RANDOM_NUM=$((1 + RANDOM % 3))
          echo "Selected GIF number: $RANDOM_NUM"
          
          # Очищаем всё между маркерами и вставляем новую ссылку
          sed -i '/<!-- START_GIF -->/,/<!-- END_GIF -->/{//!d;}' profile/README.md
          sed -i '/<!-- START_GIF -->/a \!\[space\]\(gifs/'"$RANDOM_NUM"'.gif\)' profile/README.md

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add profile/README.md
          git diff-index --quiet HEAD || git commit -m "Автообновление: установлена гифка №$RANDOM_NUM"
          git push
